export const GET_DATA = 'GET_DATA';
export const GET_DATA_PENDING = 'GET_DATA_PENDING';
export const GET_DATA_FULFILLED = 'GET_DATA_FULFILLED';
export const GET_DATA_REJECTED = 'GET_DATA_REJECTED';

export const DRAG_END = 'DRAG_END';
export const DRAG_END_FULFILLED = 'DRAG_END_FULFILLED';

export const GET_TABLE = 'GET_TABLE';
export const GET_TABLE_PENDING = 'GET_TABLE_PENDING';
export const GET_TABLE_FULFILLED = 'GET_TABLE_FULFILLED';
export const GET_TABLE_REJECTED = 'GET_TABLE_REJECTED';


export const SEARCH_PROP = 'SEARCH_PROP';
